bcgov/EPIC-FLOW

- .vscode/launch.json
- .vscode/settings.json
- reports-api/src/reports_api/resources/staff.py
> Preflight request issue #23

- reports-api/src/reports_api/models/engagement.py
- reports-api/src/reports_api/services/sync_form_data.py
#25
sync form data api
- handle nested table data inside collection of parent table datas
>  Optimize the form data sync functionality

- forms-flow-bpm/src/main/resources/processes/eao-workflows/assessment-process.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/inspection_data_record.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master-work-process.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_data_synchronization_process.bpmn
> updated workflows + enabled asynchronous continuation for handling workflow failures 

- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/SyncFormDataPipelineListener.java
> fix for work_engagement_id update

- reports-api/migrations/versions/b565204660f7_add_new_milestone_types.py
#66 Add two more milestone types for timeline extension and suspension
> add milestone types for timeline extension and suspension

- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/SyncFormDataPipelineListener.java
> update engagement_ids to formio fix

- reports-api/migrations/versions/e81a9bcad31d_add_new_events_for_new_milestone_types_.py
- reports-api/src/reports_api/models/milestone.py
#79 Add Extension and Suspension milestone to every phase
>  add milestones for milestone types Extension and Suspension

- reports-api/src/reports_api/models/phase_code.py
* added order_by clause to backref milestones on phase model
> added order_by clause to backref milestones on phase model

- reports-api/migrations/versions/99dd99e4dbbc_add_new_milestone_types_pecp_events.py
* add new milestone types for PECP related events
> Milestones (#18)

- forms-flow-bpm/src/main/resources/processes/eao-workflows/assessment-process.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/inspection_data_record.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master-work-process.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_data_synchronization_process.bpmn
> updated workflows

- reports-api/src/reports_api/models/event.py
- reports-api/src/reports_api/models/work.py
- reports-api/src/reports_api/schemas/base.py
- reports-api/src/reports_api/schemas/work.py
* backend  validations for sync api - date format fix
> backend validations

- reports-api/src/reports_api/resources/__init__.py
- reports-api/src/reports_api/resources/work.py
- reports-api/src/reports_api/schemas/work.py
- reports-api/src/reports_api/services/__init__.py
- reports-api/src/reports_api/services/work.py
#108 
added new API to check existing works based on `project_id` and `work_type_id`
> Api to check if work  exists

- reports-api/src/reports_api/models/staff.py
- reports-api/src/reports_api/resources/staff.py
- reports-api/src/reports_api/services/staff.py
Usage
API: GET `/api/v1/staffs?positions=1,2,3`
> added the functionality to search for staffs by multiple position ids

- reports-api/src/reports_api/__init__.py
- reports-api/src/reports_api/resources/staff.py
- reports-api/src/reports_api/services/code.py
- added logs to staffs API
- fixed codes API issue where limits and skip arguments caused 500 error
> fixed codes API

- forms-flow-bpm/src/main/resources/processes/eao-workflows/work.bpmn
Authentication issue fix to support asynchronous continuation.
> Fix for authentication issue when asynchronous continuation enabled

- reports-api/migrations/versions/4f89baa1d849_update_types_subtypes.py
- reports-api/src/reports_api/services/sync_form_data.py
> Migration script for types

- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CustomCommonEmailServiceListener.java
- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/data/Attachments.java
- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/data/Email.java
- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/data/TokenResponse.java
- forms-flow-bpm/src/main/resources/application-custom.yml
- forms-flow-bpm/src/main/resources/processes/eao-workflows/email-template-example.dmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/reminder_configuration_process.bpmn
* Added listener to support CHES Service
* DMN Email template and Reminder Configuration Process Diagram attached.
> Custom listener to send emails using the hosted service called CHES

- reports-api/src/reports_api/resources/__init__.py
- reports-api/src/reports_api/resources/indigenous_nation.py
- reports-api/src/reports_api/resources/project.py
- reports-api/src/reports_api/resources/proponent.py
- reports-api/src/reports_api/resources/staff.py
- reports-api/src/reports_api/services/__init__.py
- reports-api/src/reports_api/services/indigenous_nation.py
- reports-api/src/reports_api/services/project.py
- reports-api/src/reports_api/services/proponent.py
- reports-api/src/reports_api/services/staff.py
- `staffs/exists`
- `works/exists`
- `proponents/exists`
- `projects/exists`
- `indigenous-nations/exists`
Each end point is a GET, with arguments passed as query parameters
> added API endpoints for form validations:

- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CustomCommonEmailServiceListener.java
* updated CommonEmailServiceListener
> Fixed payload issues in common email service listener

- reports-api/src/reports_api/resources/__init__.py
- reports-api/src/reports_api/resources/indigenous_nation.py
- reports-api/src/reports_api/resources/project.py
- reports-api/src/reports_api/resources/proponent.py
- reports-api/src/reports_api/resources/reminder_configuration.py
- reports-api/src/reports_api/resources/staff.py
- reports-api/src/reports_api/resources/work.py
- reports-api/src/reports_api/services/__init__.py
- reports-api/src/reports_api/services/project.py
- reports-api/src/reports_api/services/proponent.py
- reports-api/src/reports_api/services/reminder_configuration.py
- reports-api/src/reports_api/services/staff.py
- reports-api/src/reports_api/services/work.py
- added validation for reminder configuration
- updated all validations to check `id` to avoid false positives in case of updates
> uniqueness check

- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CustomCommonEmailServiceListener.java
- forms-flow-bpm/src/main/resources/processes/eao-workflows/common-email-template.dmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/inspection_data_record.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_process_indigenous_nations.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_process_organisations.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_process_projects.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_process_proponents.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/master_process_staff.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/reminder_configuration.bpmn
- forms-flow-bpm/src/main/resources/processes/eao-workflows/work.bpmn
> added logic to pass dynamic due date + code cleanup + workflow fixes

- camunda-workflows/unclaim_task_process.bpmn
- forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/CustomUnclaimTaskListener.java
> Added listener to support Form claims should Time Out

- reports-api/src/reports_api/models/phase_code.py
- reports-api/wsgi.py
> added order by in phasecodes/act/work_type

- reports-api/requirements/prod.txt
- reports-api/src/reports_api/reports/resource_forecast_report.py
- added functionality to generate PDF report
- JSON response now includes `cairt_lead` if no staff is assigned
- API returns `NO CONTENT` response if no data is found
- fixed referral timing format
> resource forecast

- reports-api/src/reports_api/reports/anticipated_schedule_report.py
fixed issue where Simple amendment was not listed in anticipated schedule report
> fixed issue where Simple amendment was not listed in anticipated schedule report
